// Code generated by Slice Machine. DO NOT EDIT.

import ImageGrid from './ImageGrid';
import Sliceone from './Sliceone';

export {
	ImageGrid,
	Sliceone,
};

export const components = {
	image_grid: ImageGrid,
	sliceone: Sliceone,
};
